In [25]:
import numpy as np
import pandas as pd
netfilx=pd.read_csv('data_netflix.csv')
netfilx

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...
...,...,...,...,...,...,...,...,...,...,...,...,...
6229,80000063,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,NaN,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil..."
6230,70286564,TV Show,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,NaN,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews..."
6231,80116008,Movie,Little Baby Bum: Nursery Rhyme Friends,NaN,NaN,NaN,NaN,2016,NaN,60 min,Movies,Nursery rhymes and original music for children...
6232,70281022,TV Show,A Young Doctor's Notebook and Other Stories,NaN,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,NaN,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ..."
6233,70153404,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,NaN,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...

In [ ]:
#------head - it will display first 5 lines of  data
#------tail - it will display last 5 lines of data

In [2]:
netfilx.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...

In [3]:
netfilx.tail(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
6224,70304979,TV Show,Anthony Bourdain: Parts Unknown,NaN,Anthony Bourdain,United States,NaN,2018,TV-PG,5 Seasons,Docuseries,This CNN original series has chef Anthony Bour...
6225,70153412,TV Show,Frasier,NaN,"Kelsey Grammer, Jane Leeves, David Hyde Pierce...",United States,NaN,2003,TV-PG,11 Seasons,"Classic & Cult TV, TV Comedies",Frasier Crane is a snooty but lovable Seattle ...
6226,70243132,TV Show,La Familia P. Luche,NaN,"Eugenio Derbez, Consuelo Duval, Luis Manuel Áv...",United States,NaN,2012,TV-14,3 Seasons,"International TV Shows, Spanish-Language TV Sh...","This irreverent sitcom featues Ludovico, Feder..."
6227,80005756,TV Show,The Adventures of Figaro Pho,NaN,"Luke Jurevicius, Craig Behenna, Charlotte Haml...",Australia,NaN,2015,TV-Y7,2 Seasons,"Kids' TV, TV Comedies","Imagine your worst fears, then multiply them: ..."
6228,80159925,TV Show,Kikoriki,NaN,Igor Dmitriev,NaN,NaN,2010,TV-Y,2 Seasons,Kids' TV,A wacky rabbit and his gang of animal pals hav...
6229,80000063,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,NaN,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil..."
6230,70286564,TV Show,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,NaN,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews..."
6231,80116008,Movie,Little Baby Bum: Nursery Rhyme Friends,NaN,NaN,NaN,NaN,2016,NaN,60 min,Movies,Nursery rhymes and original music for children...
6232,70281022,TV Show,A Young Doctor's Notebook and Other Stories,NaN,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,NaN,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ..."
6233,70153404,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,NaN,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...

In [4]:
netfilx.head(150)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...
...,...,...,...,...,...,...,...,...,...,...,...,...
145,81172728,Movie,The Wedding Party 2: Destination Dubai,Niyi Akinmolayan,"Enyinna Nwigwe, Daniella Down, Banky Wellingto...",Nigeria,"September 21, 2019",2017,TV-14,98 min,"Comedies, International Movies, Romantic Movies","In this sequel to the 2016 hit ""The Wedding Pa..."
146,81095101,TV Show,Vagabond,NaN,"Lee Seung-gi, Bae Suzy, Shin Sung-rok, Moon Ju...",South Korea,"September 21, 2019",2019,TV-MA,1 Season,"International TV Shows, Korean TV Shows, TV Ac...","When his nephew dies in a plane crash, stunt m..."
147,80195173,TV Show,Battlefish,NaN,NaN,NaN,"September 21, 2018",2018,TV-MA,1 Season,"Reality TV, Science & Nature TV, TV Action & A...","Over the course of a fishing season, tough men..."
148,80241960,TV Show,DRAGON PILOT: Hisone & Masotan,NaN,"Misaki Kuno, Tomoyo Kurosawa, Maki Kawase, Sat...",Japan,"September 21, 2018",2018,TV-14,1 Season,"Anime Series, International TV Shows",Recently stationed Air Self-Defense Force rook...
149,80115346,TV Show,Hilda,NaN,"Bella Ramsey, Ameerah Falzon-Ojo, Oliver Nelso...","United Kingdom, Canada, United States","September 21, 2018",2018,TV-Y7,1 Season,Kids' TV,"Fearless, free-spirited Hilda finds new friend..."

In [5]:
netfilx.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6234 entries, 0 to 6233
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       6234 non-null   int64
 1   type          6234 non-null   object
 2   title         6234 non-null   object
 3   director      4265 non-null   object
 4   cast          5664 non-null   object
 5   country       5758 non-null   object
 6   date_added    6223 non-null   object
 7   release_year  6234 non-null   int64
 8   rating        6224 non-null   object
 9   duration      6234 non-null   object
 10  listed_in     6234 non-null   object
 11  description   6234 non-null   object
dtypes: int64(2), object(10)
memory usage: 584.6+ KB

In [6]:
netfilx.index

RangeIndex(start=0, stop=6234, step=1)

In [7]:
netfilx.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [8]:
netfilx.loc[1226]

show_id                                                  81073633
type                                                        Movie
title                                  Iliza Shlesinger: Unveiled
director                                              Steve Paley
cast                                             Iliza Shlesinger
country                                             United States
date_added                                      November 19, 2019
release_year                                                 2019
rating                                                      TV-MA
duration                                                   78 min
listed_in                                         Stand-Up Comedy
description     Here comes the bride, and she's got plenty to ...
Name: 1226, dtype: object

In [9]:
netfilx['release_year'].min()

1925

In [10]:
netfilx[netfilx['release_year'] == 2019]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
34,80221550,TV Show,Archibald's Next Big Thing,NaN,"Tony Hale, Rosamund Pike, Jordan Fisher, Chels...",NaN,"September 6, 2019",2019,TV-Y7,1 Season,"Kids' TV, TV Comedies",Happy-go-lucky chicken Archibald may not remem...
35,81154455,Movie,Article 15,Anubhav Sinha,"Ayushmann Khurrana, Nassar, Manoj Pahwa, Kumud...",India,"September 6, 2019",2019,TV-MA,125 min,"Dramas, International Movies, Thrillers",The grim realities of caste discrimination com...
38,81132437,Movie,Kill Me If You Dare,Şenol Sönmez,"Murat Boz, Seda Bakan, Açelya Topaloğlu, Özgür...",NaN,"September 6, 2019",2019,TV-14,100 min,"Comedies, International Movies, Romantic Movies","Bogged down with money problems, a couple grow..."
39,80178151,TV Show,The Spy,NaN,"Sacha Baron Cohen, Noah Emmerich, Hadar Ratzon...",France,"September 6, 2019",2019,TV-MA,1 Season,"International TV Shows, TV Dramas, TV Thrillers","In the 1960s, Israeli clerk-turned-secret agen..."
...,...,...,...,...,...,...,...,...,...,...,...,...
6198,80189829,TV Show,The Protector,NaN,"Çağatay Ulusoy, Ayça Ayşin Turan, Hazar Ergüçl...",Turkey,"April 26, 2019",2019,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",Discovering his ties to a secret ancient order...
6204,80091341,TV Show,Cuckoo,NaN,"Andy Samberg, Taylor Lautner, Greg Davies, Hel...",United Kingdom,"April 19, 2019",2019,TV-14,5 Seasons,"British TV Shows, International TV Shows, TV C...",Rachel shocks her proper British parents when ...
6206,80173174,TV Show,Samantha!,NaN,"Emmanuelle Araújo, Douglas Silva, Sabrina Nona...",Brazil,"April 19, 2019",2019,TV-MA,2 Seasons,"International TV Shows, TV Comedies","A child star in the '80s, Samantha clings to t..."
6215,80066227,TV Show,Crazy Ex-Girlfriend,NaN,"Rachel Bloom, Vincent Rodriguez III, Santino F...",United States,"April 13, 2019",2019,TV-14,4 Seasons,"Romantic TV Shows, TV Comedies","Still pining for Josh, the boy who dumped her ..."
6219,80186475,TV Show,Pokémon the Series,NaN,"Sarah Natochenny, Laurie Hymes, Jessica Paquet...",Japan,"April 1, 2019",2019,TV-Y7-FV,2 Seasons,"Anime Series, Kids' TV",Ash and his Pikachu travel to the Alola region...

In [11]:
netfilx[netfilx['release_year'] == 2003]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
311,60031232,Movie,Mystic River,Clint Eastwood,"Sean Penn, Tim Robbins, Kevin Bacon, Laurence ...","United States, Australia","September 1, 2019",2003,R,138 min,"Dramas, Thrillers","Tragedy reunites childhood friends Sean, Dave ..."
372,70036200,Movie,Inuyasha the Movie - La spada del dominatore d...,Toshiya Shinohara,"Kappei Yamaguchi, Satsuki Yukino, Koji Tsujita...",Japan,"September 1, 2017",2003,NR,99 min,"Action & Adventure, Anime Features, Internatio...",The Great Dog Demon beaqueathed one of the Thr...
782,60029167,Movie,Bad Boys II,Michael Bay,"Will Smith, Martin Lawrence, Jordi Mollà, Gabr...",United States,"October 1, 2019",2003,R,147 min,"Action & Adventure, Comedies","In this hyperkinetic sequel, a pair of Miami n..."
786,60027726,Movie,Charlie's Angels: Full Throttle,McG,"Cameron Diaz, Drew Barrymore, Lucy Liu, Bernie...",United States,"October 1, 2019",2003,PG-13,106 min,"Action & Adventure, Comedies","In this reboot of the TV classic, the Angels a..."
791,60027716,Movie,Dumb and Dumberer: When Harry Met Lloyd,Troy Miller,"Eric Christian Olsen, Derek Richardson, Rachel...",United States,"October 1, 2019",2003,PG-13,85 min,Comedies,This wacky prequel to the 1994 blockbuster goe...
1263,81179844,TV Show,At the Dolphin Bay,NaN,"Angela Chang, Ambrose Hui, Wallace Huo, Jill H...",Taiwan,"November 15, 2019",2003,TV-14,1 Season,"International TV Shows, Romantic TV Shows",Encountering each other after a long separatio...
1282,81179864,TV Show,Westside Story,NaN,"Tony Sun, Wallace Huo, Esther Liu, Cyndi Wang,...",NaN,"November 15, 2019",2003,TV-14,1 Season,"International TV Shows, Romantic TV Shows, TV ...",Spirited high school misfits with hearts of go...
1350,60027583,Movie,Anger Management,Peter Segal,"Adam Sandler, Jack Nicholson, Marisa Tomei, Lu...",United States,"November 1, 2019",2003,PG-13,105 min,Comedies,After a gentle businessman is forced to get an...
1373,60031247,Movie,Gothika,Mathieu Kassovitz,"Halle Berry, Robert Downey Jr., Charles S. Dut...","United States, France, Canada, Spain","November 1, 2019",2003,R,98 min,"Horror Movies, Thrillers","After a car crash, a criminal psychiatrist awa..."
1423,60027695,Movie,The Matrix Reloaded,"Lilly Wachowski, Lana Wachowski","Keanu Reeves, Laurence Fishburne, Carrie-Anne ...",United States,"November 1, 2019",2003,R,138 min,"Action & Adventure, Sci-Fi & Fantasy","The crew must protect Zion, the last outpost s..."
1424,60031303,Movie,The Matrix Revolutions,"Lilly Wachowski, Lana Wachowski","Keanu Reeves, Laurence Fishburne, Carrie-Anne ...",United States,"November 1, 2019",2003,R,129 min,"Action & Adventure, Sci-Fi & Fantasy",The final installment in the Matrix trilogy fi...
1600,80047032,TV Show,Pasión de Gavilanes,NaN,"Danna García, Mario Cimarro, Paola Rey, Jorge ...","Colombia, United States","May 4, 2017",2003,TV-14,1 Season,"International TV Shows, Romantic TV Shows, Spa...",Three brothers seek to avenge the tragic death...
1750,70007056,Movie,Kucch To Hai,Anil V. Kumar,"Tusshar Kapoor, Esha Deol, Natasha, Jeetendra,...",India,"May 15, 2019",2003,TV-14,136 min,"Dramas, International Movies, Thrillers",A student tries to steal a test from a teacher...
1817,60031264,Movie,Dr. Seuss' The Cat in the Hat,Bo Welch,"Mike Myers, Alec Baldwin, Kelly Preston, Dakot...",United States,"May 1, 2019",2003,PG,82 min,"Children & Family Movies, Comedies","While Mom is away, a bored little boy and girl..."
2331,60036746,Movie,Boom,Kaizad Gustad,"Amitabh Bachchan, Gulshan Grover, Jackie Shrof...",India,"March 1, 2018",2003,TV-MA,79 min,"Action & Adventure, Dramas, International Movies","Following a fashion show mishap, three supermo..."
2336,60036617,Movie,Dum,Eeshwar Nivas,"Vivek Oberoi, Diya Mirza, Atul Kulkarni, Govin...",India,"March 1, 2018",2003,TV-14,162 min,"Action & Adventure, Dramas, International Movies",When one of his colleagues becomes corrupted b...
2354,80223317,Movie,Khushi,"Surya S.J., Sunil Kumar Agrawal","Fardeen Khan, Kareena Kapoor, Amrish Puri, Nav...",India,"March 1, 2018",2003,TV-14,157 min,"Comedies, International Movies, Music & Musicals",While playing matchmaker to a pair of their fr...
2714,60026155,Movie,What a Girl Wants,Dennie Gordon,"Amanda Bynes, Colin Firth, Kelly Preston, Eile...",United States,"June 1, 2019",2003,PG,105 min,"Children & Family Movies, Comedies","In search of the father she's never met, the d..."
3087,60027701,Movie,The In-Laws,Andrew Fleming,"Michael Douglas, Albert Brooks, Robin Tunney, ...","United States, Germany, Canada","July 1, 2019",2003,PG-13,98 min,"Action & Adventure, Comedies",Daredevil secret agent and father of the groom...
3096,60036112,Movie,Chalte Chalte,Aziz Mirza,"Shah Rukh Khan, Rani Mukerji, Jas Arora, Satis...",India,"July 1, 2018",2003,TV-PG,166 min,"Dramas, International Movies, Romantic Movies",Priya and Raj are polar opposites. Raj is bras...
3109,60029032,Movie,Melvin Goes to Dinner,Bob Odenkirk,"Michael Blieden, Stephanie Courtney, Annabelle...",United States,"July 1, 2018",2003,R,84 min,"Comedies, Dramas, Independent Movies","When Melvin and his friends gather for dinner,..."
3510,60026114,Movie,Final Destination 2,David R. Ellis,"Ali Larter, A.J. Cook, Michael Landes, Terrenc...","United States, Canada","January 1, 2020",2003,R,90 min,"Horror Movies, Thrillers","On a road trip with friends, Kimberly has a pr..."
3530,60031236,Movie,Kill Bill: Vol. 1,Quentin Tarantino,"Uma Thurman, Lucy Liu, Vivica A. Fox, Daryl Ha...","United States, Japan","January 1, 2020",2003,R,111 min,Action & Adventure,"An assassin is shot by her ruthless employer, ..."
3569,60029154,Movie,Terminator 3: Rise of the Machines,Jonathan Mostow,"Arnold Schwarzenegger, Nick Stahl, Claire Dane...","United States, Germany, United Kingdom","January 1, 2020",2003,R,109 min,"Action & Adventure, Sci-Fi & Fantasy",Ten years after John Connor saved Earth from J...
3580,60004484,Movie,The Lord of the Rings: The Return of the King,Peter Jackson,"Elijah Wood, Ian McKellen, Liv Tyler, Viggo Mo...","New Zealand, United States","January 1, 2020",2003,PG-13,201 min,"Action & Adventure, Sci-Fi & Fantasy",Aragorn is revealed as the heir to the ancient...
3609,60027689,Movie,Daddy Day Care,Steve Carr,"Eddie Murphy, Jeff Garlin, Steve Zahn, Regina ...",United States,"January 1, 2019",2003,PG,93 min,"Children & Family Movies, Comedies",When a conscientious father loses his lucrativ...
3624,60031284,Movie,Mona Lisa Smile,Mike Newell,"Julia Roberts, Kirsten Dunst, Julia Stiles, Ma...",United States,"January 1, 2019",2003,PG-13,119 min,Dramas,"In 1953, the women of Wellesley College are me..."
3631,60026139,Movie,Tears of the Sun,Antoine Fuqua,"Bruce Willis, Monica Bellucci, Cole Hauser, Ea...",United States,"January 1, 2019",2003,R,121 min,"Action & Adventure, Dramas",A Navy SEAL is sent to a war-torn African jung...
3651,70204980,TV Show,Fullmetal Alchemist,NaN,"Romi Park, Rie Kugimiya, Megumi Toyoguchi, Miy...",Japan,"January 1, 2018",2003,TV-14,1 Season,"Anime Series, International TV Shows",Brothers Edward and Alphonse use alchemy to re...
3721,70213079,TV Show,Power Rangers Ninja Storm,NaN,"Pua Magasiva, Sally Martin, Glenn McMillan, Ad...","United States, New Zealand","January 1, 2016",2003,TV-Y7-FV,1 Season,Kids' TV,When the elite warriors from the Wind Ninja Ac...
4099,70035037,Movie,The Gathering,Nia Dinata,"Cut Mini Theo, Tora Sudiro, Aida Nurmala, Sury...",Indonesia,"December 8, 2018",2003,TV-14,124 min,"Comedies, Dramas, International Movies","Between divorce, bad relationships and coming ..."
4169,60034116,Movie,3 Deewarein,Nagesh Kukunoor,"Naseeruddin Shah, Jackie Shroff, Juhi Chawla, ...",NaN,"December 31, 2019",2003,TV-MA,121 min,"Dramas, International Movies, Thrillers",A reporter interviews three convicts on death ...
4183,81213889,Movie,Bhoot,Ram Gopal Varma,"Ajay Devgn, Urmila Matondkar, Nana Patekar, Re...",India,"December 31, 2019",2003,TV-MA,114 min,"Horror Movies, International Movies, Thrillers","After a couple moves into an apartment, the wi..."
4424,60030245,Movie,George of the Jungle 2,David Grossman,"Christopher Showerman, Julie Benz, Angus T. Jo...","United States, Australia","December 20, 2016",2003,PG,87 min,"Children & Family Movies, Comedies","Now married and raising a son, clumsy ape-man ..."
5058,60032685,Movie,Darna Mana Hai,Prawal Raman,"Aftab Shivdasani, Antara Mali, Boman Irani, Is...",India,"August 1, 2019",2003,TV-MA,116 min,"Horror Movies, International Movies, Thrillers",Stranded in a jungle when their car breaks dow...
5079,60031278,Movie,Something's Gotta Give,Nancy Meyers,"Jack Nicholson, Diane Keaton, Keanu Reeves, Fr...",United States,"August 1, 2019",2003,PG-13,128 min,"Comedies, Romantic Movies","Still sexy at 60, Harry Sanborn wines and dine..."
5403,70040077,Movie,Hazaaron Khwaishein Aisi,Sudhir Mishra,"Kay Kay Menon, Shiney Ahuja, Chitrangada Singh...","India, France","April 15, 2019",2003,TV-MA,111 min,"Dramas, International Movies, Romantic Movies","In a politically charged India of the 1970s, t..."
5404,60031998,Movie,Jhankaar Beats,Sujoy Ghosh,"Rahul Bose, Sanjay Suri, Rinke Khanna, Riya Se...",India,"April 15, 2019",2003,TV-MA,131 min,"Comedies, International Movies, Music & Musicals",Juggling personal predicaments and workplace w...
5405,60036103,Movie,Mumbai Matinee,Anant Balani,"Rahul Bose, Vijay Raaz, Anusha Dhandekar, Peri...",India,"April 15, 2019",2003,TV-14,116 min,"Comedies, International Movies, Romantic Movies","Still a virgin at 32 years old, a frustrated a..."
5489,60029178,Movie,Spy Kids 3: Game Over,Robert Rodriguez,"Daryl Sabara, Sylvester Stallone, Ricardo Mont...",United States,"April 1, 2019",2003,PG,83 min,"Children & Family Movies, Comedies",Carmen gets caught in a virtual reality game d...
5725,80136795,TV Show,Kopitiam,NaN,"Joanna Bessey, Douglas Lim, Lina Teoh, Rashid ...",Malaysia,"November 3, 2018",2003,TV-14,7 Seasons,"International TV Shows, TV Comedies",A young woman returns to Malaysia to take over...
6225,70153412,TV Show,Frasier,NaN,"Kelsey Grammer, Jane Leeves, David Hyde Pierce...",United States,NaN,2003,TV-PG,11 Seasons,"Classic & Cult TV, TV Comedies",Frasier Crane is a snooty but lovable Seattle ...
6233,70153404,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,NaN,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...

In [12]:
size=len(netfilx['title'])
size

6234

In [13]:
#drop -- going to remove the particular column
netfilx.drop('director',axis=1)

,show_id,type,title,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...
...,...,...,...,...,...,...,...,...,...,...,...
6229,80000063,TV Show,Red vs. Blue,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,NaN,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil..."
6230,70286564,TV Show,Maron,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,NaN,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews..."
6231,80116008,Movie,Little Baby Bum: Nursery Rhyme Friends,NaN,NaN,NaN,2016,NaN,60 min,Movies,Nursery rhymes and original music for children...
6232,70281022,TV Show,A Young Doctor's Notebook and Other Stories,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,NaN,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ..."
6233,70153404,TV Show,Friends,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,NaN,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...

In [14]:
netfilx.describe()

            show_id  release_year
count  6.234000e+03    6234.00000
mean   7.670368e+07    2013.35932
std    1.094296e+07       8.81162
min    2.477470e+05    1925.00000
25%    8.003580e+07    2013.00000
50%    8.016337e+07    2016.00000
75%    8.024489e+07    2018.00000
max    8.123573e+07    2020.00000

In [15]:
netfilx.shape

(6234, 12)

In [16]:
netfilx.duplicated().sum()

np.int64(0)

In [17]:
netfilx.isnull().sum()

show_id            0
type               0
title              0
director        1969
cast             570
country          476
date_added        11
release_year       0
rating            10
duration           0
listed_in          0
description        0
dtype: int64

In [18]:
netfilx[['title','listed_in','duration']]

,title,listed_in,duration
0,Norm of the North: King Sized Adventure,"Children & Family Movies, Comedies",90 min
1,Jandino: Whatever it Takes,Stand-Up Comedy,94 min
2,Transformers Prime,Kids' TV,1 Season
3,Transformers: Robots in Disguise,Kids' TV,1 Season
4,#realityhigh,Comedies,99 min
...,...,...,...
6229,Red vs. Blue,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...",13 Seasons
6230,Maron,TV Comedies,4 Seasons
6231,Little Baby Bum: Nursery Rhyme Friends,Movies,60 min
6232,A Young Doctor's Notebook and Other Stories,"British TV Shows, TV Comedies, TV Dramas",2 Seasons
6233,Friends,"Classic & Cult TV, TV Comedies",10 Seasons

In [19]:
# IMDB   -- Internet movie database
import numpy as np
IMDB =np.random.uniform(low=0,high=10,size=len(netfilx['title']))
IMDB=np.around(IMDB,decimals=2)
# adding the 'IMDB rating' column as a new column
netfilx['IMDB rating']=IMDB
netfilx

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,IMDB rating
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...,4.42
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...,2.41
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob...",0.93
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...,3.45
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...,0.81
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6229,80000063,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,NaN,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil...",7.92
6230,70286564,TV Show,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,NaN,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews...",1.56
6231,80116008,Movie,Little Baby Bum: Nursery Rhyme Friends,NaN,NaN,NaN,NaN,2016,NaN,60 min,Movies,Nursery rhymes and original music for children...,5.92
6232,70281022,TV Show,A Young Doctor's Notebook and Other Stories,NaN,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,NaN,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ...",6.87
6233,70153404,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,NaN,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...,0.93

In [20]:
netfilx[netfilx.isnull().any(axis=1)]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,IMDB rating
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...,2.41
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob...",0.93
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...,3.45
5,80163890,TV Show,Apaches,NaN,"Alberto Ammann, Eloy Azorín, Verónica Echegui,...",Spain,"September 8, 2017",2016,TV-MA,1 Season,"Crime TV Shows, International TV Shows, Spanis...",A young journalist is forced into a life of cr...,7.47
8,80117902,TV Show,Fire Chasers,NaN,NaN,United States,"September 8, 2017",2017,TV-MA,1 Season,"Docuseries, Science & Nature TV","As California's 2016 fire season rages, brave ...",6.52
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6229,80000063,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,NaN,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil...",7.92
6230,70286564,TV Show,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,NaN,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews...",1.56
6231,80116008,Movie,Little Baby Bum: Nursery Rhyme Friends,NaN,NaN,NaN,NaN,2016,NaN,60 min,Movies,Nursery rhymes and original music for children...,5.92
6232,70281022,TV Show,A Young Doctor's Notebook and Other Stories,NaN,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,NaN,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ...",6.87
6233,70153404,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,NaN,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...,0.93

In [21]:
# drop item which have missing values in any of the column
netfilx.dropna()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,IMDB rating
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...,4.42
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...,0.81
6,70304989,Movie,Automata,Gabe Ibáñez,"Antonio Banderas, Dylan McDermott, Melanie Gri...","Bulgaria, United States, Spain, Canada","September 8, 2017",2014,R,110 min,"International Movies, Sci-Fi & Fantasy, Thrillers","In a dystopian future, an insurance adjuster f...",0.39
7,80164077,Movie,Fabrizio Copano: Solo pienso en mi,"Rodrigo Toro, Francisco Schultz",Fabrizio Copano,Chile,"September 8, 2017",2017,TV-MA,60 min,Stand-Up Comedy,Fabrizio Copano takes audience participation t...,6.16
9,70304990,Movie,Good People,Henrik Ruben Genz,"James Franco, Kate Hudson, Tom Wilkinson, Omar...","United States, United Kingdom, Denmark, Sweden","September 8, 2017",2014,R,90 min,"Action & Adventure, Thrillers",A struggling couple can't believe their luck w...,2.18
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6142,80063224,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"August 30, 2019",2019,TV-PG,7 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...,5.90
6158,80164216,TV Show,Miraculous: Tales of Ladybug & Cat Noir,Thomas Astruc,"Cristina Vee, Bryce Papenbrook, Keith Silverst...","France, South Korea, Japan","August 2, 2019",2018,TV-Y7,4 Seasons,"Kids' TV, TV Action & Adventure","When Paris is in peril, Marinette becomes Lady...",8.80
6167,80115328,TV Show,Sacred Games,"Vikramaditya Motwane, Anurag Kashyap","Saif Ali Khan, Nawazuddin Siddiqui, Radhika Ap...","India, United States","August 15, 2019",2019,TV-MA,2 Seasons,"Crime TV Shows, International TV Shows, TV Dramas",A link in their pasts leads an honest cop to a...,8.16
6182,80176842,TV Show,Men on a Mission,Jung-ah Im,"Ho-dong Kang, Soo-geun Lee, Sang-min Lee, Youn...",South Korea,"April 9, 2019",2019,TV-14,4 Seasons,"International TV Shows, Korean TV Shows, Stand...",Male celebs play make-believe as high schooler...,4.48
6213,80126599,TV Show,Leyla and Mecnun,Onur Ünlü,"Ali Atay, Melis Birkan, Serkan Keskin, Ahmet M...",Turkey,"April 15, 2017",2014,TV-PG,3 Seasons,"International TV Shows, Romantic TV Shows, TV ...",Destiny brings Mecnun and Leyla together as ne...,6.52

In [23]:
netfilx.replace({'country':{'United States':'US','United Kingdom':'UK'}})

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,IMDB rating
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...,4.42
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,UK,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...,2.41
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",US,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob...",0.93
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",US,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...,3.45
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",US,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...,0.81
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6229,80000063,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",US,NaN,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil...",7.92
6230,70286564,TV Show,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",US,NaN,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews...",1.56
6231,80116008,Movie,Little Baby Bum: Nursery Rhyme Friends,NaN,NaN,NaN,NaN,2016,NaN,60 min,Movies,Nursery rhymes and original music for children...,5.92
6232,70281022,TV Show,A Young Doctor's Notebook and Other Stories,NaN,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",UK,NaN,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ...",6.87
6233,70153404,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",US,NaN,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...,0.93

In [ ]:
 z# get max min and mean of the 'IMDBB rating' using agg()
netfilx['IMDB rating'].agg(['max','min','mean'])

max     10.000000
min      0.000000
mean     4.992892
Name: IMDB rating, dtype: float64

In [ ]:
netfilx[netfilx['IMDB rating']==6]

,show_id,type,title,cast,country,date_added,release_year,rating,duration,listed_in,description,IMDB rating
566,15815343,Movie,The Texas Chainsaw Massacre,"Gunnar Hansen, Jim Siedow, Marilyn Burns, Edwi...",United States,"October 22, 2019",1974,R,83 min,"Cult Movies, Horror Movies, Independent Movies",When some friends visit a vandalized graveyard...,6.0
884,80187618,Movie,Manje Bistre,"Gippy Grewal, Sonam Bajwa, Karamjit Anmol, Jag...",India,"October 1, 2018",2017,TV-PG,136 min,"Comedies, Dramas, International Movies","While prepping for a family wedding, a young m...",6.0
2199,80226021,Movie,Jag älskar dig: En skilsmässokomedi,"Björn Kjellman, Christine Meltzer, Rodolfo Cor...",Sweden,"March 15, 2018",2016,TV-MA,91 min,"Comedies, Dramas, International Movies","Tired of her passionless marriage, Marianne wa...",6.0
2491,80190144,Movie,The House on Coco Road,NaN,United States,"June 30, 2017",2016,TV-14,79 min,Documentaries,This film chronicles the journey of Fannie Hau...,6.0
2983,80081277,Movie,Colonia,"Emma Watson, Daniel Brühl, Michael Nyqvist, Ri...","Germany, France, Luxembourg, United Kingdom, U...","July 14, 2018",2015,R,110 min,"Dramas, Independent Movies, International Movies",When her boyfriend is caught up in a Chilean c...,6.0
3764,81044300,TV Show,The Last of the Schmucks,"Chico, Ahmed Mekky, Hesham Maged, Bayoumi Foua...",Egypt,"February 7, 2019",2017,TV-MA,1 Season,"International TV Shows, TV Comedies",The year is 2041 and a dispute between a man a...,6.0
4323,80244708,Movie,When Angels Sleep,"Julián Villagrán, Marian Álvarez, Ester Expósi...",Spain,"December 28, 2018",2018,TV-MA,96 min,"Dramas, International Movies, Thrillers",After a businessman falls asleep at the wheel ...,6.0
4501,70001237,Movie,Lakshya,"Amitabh Bachchan, Hrithik Roshan, Preity Zinta...",India,"December 15, 2019",2004,TV-14,185 min,"Action & Adventure, Dramas, International Movies","After dropping out of the army, a spoiled teen...",6.0